DW-42021-prj-grp1-Luangxay/project2_products/item/urls.py
# item/urls.py
from django.urls import path
from . import views
from .views import ItemsListView, ItemCreateView, ItemDetailView, LikeView, ItemUpdateView, ItemDeleteView, SearchItemView, FilterItemView, CommentFormView, FlagView

urlpatterns = [
    path("items/new/", ItemCreateView.as_view(), name="item-create"),
    path("", views.home, name="home"),
    path("items/", ItemsListView.as_view(), name="items"),
    path("items/<int:pk>/", ItemDetailView.as_view(), name="item-detail"),
    path("like/<int:pk>", LikeView, name="like_item"),
    path("items/<int:pk>/update", ItemUpdateView.as_view(), name="item-update"),
    path("items/<int:pk>/delete", ItemDeleteView.as_view(), name="item-delete"),
    path("search/", SearchItemView.as_view(), name="item-search"),
    path("filter/", FilterItemView.as_view(), name="item-filter"),
    path("items/<int:pk>/comment", CommentFormView.as_view(), name="item-comment"),
    path("flag/<int:pk>", FlagView, name="flag_item")
]

DW-42021-prj-grp1-Luangxay/project2_products/item/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse

# Choices for status of the item
STATUS_CHOICES = (
    ('new','New'),
    ('used','Used')
)

# Choices for the genre of the item
GENRE_CHOICES = (
    ('food', 'Food'),
    ('book', 'Books'),
    ('clothing', 'Clothing'),
    ('electronics', 'Electronics'),
    ('instrument', 'Instrument')
)


# Item model, with all the relevant information to a product being sold
class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    itemname = models.CharField(max_length=150)
    genre = models.CharField(max_length=100, choices=GENRE_CHOICES)
    description = models.TextField(max_length=300, default='Describe your item.')
    price = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=4, choices=STATUS_CHOICES)
    date_posted = models.DateTimeField(default=timezone.now)
    likes = models.ManyToManyField(User, related_name='product_item')
    flagged = models.ManyToManyField(User, related_name='flagged_item')
    itempic = models.ImageField(upload_to='item_pic/', default='item_pic/item_default.PNG')

    # Redirecting to the url after the item is created, override
    def get_absolute_url(self):
        return reverse('item-detail', kwargs={'pk':self.pk})

    # Returns the total number of likes a specific item has
    def getTotalLikes(self):
        return self.likes.count()


# Comment associated to an Item model
class ItemComment(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=25, default="")
    comment = models.TextField(max_length=300, default="")
    rating = models.DecimalField(max_digits=2, decimal_places=1, default=2.5, validators=[MinValueValidator(0), MaxValueValidator(5)])
    date_posted = models.DateTimeField(default=timezone.now)

    # Redirect after the comment is made
    def get_absolute_url(self):
        return reverse('item-detail', kwargs={'pk':self.item.pk})

DW-42021-prj-grp1-Luangxay/project2_products/item/views.py
#item/views
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render, get_object_or_404
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from .models import Item, ItemComment
from django.db.models import Avg, Count


# ListView for all of the items, displays all of the items in the database
class ItemsListView(ListView):
    model = Item
    template_name = "item/items.html"
    paginate_by = 10


# CreateView to create an item and add it to the database
class ItemCreateView(LoginRequiredMixin, CreateView):
    model = Item
    fields = ['itemname', 'genre', 'description', 'price', 'status']

    # Checks for form validity, override
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


# DetailView of each item, shows more detailed information
class ItemDetailView(DetailView):
    model = Item
    template_name = "item/itemDetail.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        averagerating = ItemComment.objects.filter(item_id=self.kwargs['pk']).aggregate(Avg('rating'))
        if averagerating.get('rating__avg') is not None:
            context['avgRating'] = round(averagerating.get('rating__avg'), 1)
        else:
            context['avgRating'] = 0
        return context


# Form to update the information about an item, permitted depending on group and owner
class ItemUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Item
    fields = ['itemname', 'genre', 'description', 'price', 'itempic', 'status']

    # User must pass the conditions to be able to edit the item
    def test_func(self):
        item = self.get_object()

        is_owner = self.request.user == item.user
        is_admin_item_gp = str(self.request.user.groups.all()[0]) == "admin_item_gp"
        is_admin_gp = str(self.request.user.groups.all()[0]) == "admin_gp"

        return is_owner or is_admin_gp or is_admin_item_gp


# DeleteView to delete the item from the database, depending on group and owner
class ItemDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Item
    success_url = '/items'

    # User must pass the conditions to be able to delete the item
    def test_func(self):
        item = self.get_object()

        is_owner = self.request.user == item.user
        is_admin_item_gp = str(self.request.user.groups.all()[0]) == "admin_item_gp"
        is_admin_gp = str(self.request.user.groups.all()[0]) == "admin_gp"

        return is_owner or is_admin_gp or is_admin_item_gp


# CreateView to add a comment to an existing item
class CommentFormView(LoginRequiredMixin, CreateView):
    model = ItemComment
    fields = ['title', 'comment', 'rating']
    template_name = "item/item_comment_form.html"

    # Checks form validity, override
    def form_valid(self, form):
        item = get_object_or_404(Item, id=self.kwargs['pk'])
        form.instance.user = self.request.user
        form.instance.item = item
        return super().form_valid(form)


# ListView that shows the search results and shows the ones that match the search query
class SearchItemView(ListView):
    model = Item
    template_name = "item/items.html"

    # Uses the searched term to return the list of items that match the search query
    def get_queryset(self):
        search = self.request.GET.get('search')
        if search:
            result = Item.objects.filter(itemname__icontains=search)
            count = len(result)

            if count > 0:
                messages.success(self.request, "{0} matches".format(count))
            else:
                messages.error(self.request, "no matches")
            return result

        else:
            return Item.objects.all()


# ListView that shows the results of the filter
class FilterItemView(ListView):
    model = Item
    template_name = "item/items.html"

    # Uses the filtered term to return the list of items that match the filter query
    def get_queryset(self):
        filtered = self.request.GET.get('filterby')
        if filtered == "all":
            return Item.objects.all()
        elif filtered == "likes":
            return Item.objects.annotate(count=Count('likes')).order_by('-count')
        else:
            result = Item.objects.filter(genre__icontains=filtered)
            return result


# Function that shows the home page
def home(request):
    return render(request, "item/home.html")


# Function that lets the users like, with each user only being able to like one per item
def LikeView(request, pk):
    item = get_object_or_404(Item, id=request.POST.get('item_id'))
    if request.user in item.likes.all():
        item.likes.remove(request.user)
    else:
        item.likes.add(request.user)
    return HttpResponseRedirect(reverse('item-detail', args=[str(pk)]))


# Function that lets the user flag
def FlagView(request, pk):
    item = get_object_or_404(Item, id=request.POST.get('item_id'))
    if request.user in item.flagged.all():
        item.flagged.remove(request.user)
    else:
        item.flagged.add(request.user)
    return HttpResponseRedirect(reverse('item-detail', args=[str(pk)]))

DW-42021-prj-grp1-Luangxay/project2_products/item/templates/item/home.html
{% extends "base.html" %}

{% block title %}
    Home
{% endblock title %}

{% block cssLink %}
{% load static %}
<link type="text/css" rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock %}

{% block content %}
{% if request.user.profile.warn > 0  %}
    <div id="warning">
        You have been warned: {{ request.user.profile.warn }}x * If you are warned more than 3 times, you will be BANNED!
    </div>

{% endif %}

<h2> Home </h2>
{% load static %}
<img id="homeImg" src="{% static 'images/onlineShop.jpg' %}">
{% endblock %}

DW-42021-prj-grp1-Luangxay/project2_products/item/templates/item/itemDetail.html
{% extends "base.html" %}
{% load static %}

{% block title%}
    Item Detail
{% endblock title%}

{% block cssLink %}
<!--<link type="text/css" rel="stylesheet" href="{% static 'item/items.css' %}">-->
<link type="text/css" rel="stylesheet" href="{% static 'item/productDetail.css' %}">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap" rel="stylesheet">
{% endblock %}

{% block content %}
<div id="detailContainer">
    <section id="infoContainer">
        <h2>{{ object.itemname }}</h2>
        <div id="info">
            <div id="imgContainer">
                <img src="{{ object.itempic.url }}">
            </div>
            <div id="details">
                <div class="row"><label id="seller">Seller:</label><p>{{ object.user.first_name }} {{ object.user.last_name }}</p></div>
                <div class="row"><label id="address">Address:</label><p>{{ object.user.profile.address }}</p></div>
                <div class="row"><label id="genre">Genre:</label><p>{{ object.genre }}</p></div>
                <div class="row"><label id="price">Price:</label><p>{{ object.price }}$</p></div>
                <div class="row"><label id="status">Status:</label><p>{{ object.status }}</p></div>
                <div class="row"><label class="dateposted">Date posted:</label><p>{{ object.date_posted }}</p></div>
                <div class="descRow"><label id="description">Description:</label><textarea readonly>{{ object.description }}</textarea></div>
                <div class="row"><label id="likes">Likes:</label><p>{{ object.likes.count }}</p></div>
                <div class="row"><label>Flags:</label><p>{{ object.flagged.count }}</p></div>
                <div class="row"><label>Rating:</label><p>{{ avgRating }}★</p></div>
            </div>
        </div>
        <div id="btnContainer">
            <div>
            {% if user.is_authenticated %}
                <form action="{% url 'like_item' object.pk %}" method="POST" id="likeform">
                    {% csrf_token %}
                    <button type="submit" name="item_id" value="{{ object.id }}" id="likebutton">Like {% if request.user in object.likes.all %}💗{% endif %}</button>
                </form>
                <form action="{% url 'flag_item' object.pk %}" method="POST" id="flagform">
                    {% csrf_token %}
                    <button type="submit" name="item_id" value="{{ object.id }}" id="flagbutton">Flag {% if request.user in object.flagged.all %}🚩{%endif%}</button>
                </form>
                <button id="addCommentBtn" onclick="window.location.href='/items/{{ item.id }}/comment'">Add Comment 💬</button>
            {% endif %}
            </div>
            <div>
                {% if object.user == user or request.user.groups.all.0.name == "admin_gp" or request.user.groups.all.0.name == "admin_item_gp"%}
                    <button id="editbutton" onclick="window.location.href='/items/{{ item.id }}/update'">Edit 📝</button>
                    <button id="deletebutton" onclick="window.location.href='/items/{{ item.id }}/delete'">Delete ❌</button>
                {% endif %}
            </div>
        </div>
    </section>
    <h2>Comments</h2>
    <section id="commentsContainer">
        {% for comments in object.itemcomment_set.all %}
        <div class="individualComments">
            <div class="descRow">
                <h3 class="commentTitle">{{ comments.title }}</h3>
                <textarea readonly class="commentDesc">{{ comments.comment }}</textarea>
            </div>
            <div class="row"><label class="commentuser">Author: </label><p>{{ comments.user.first_name }} {{ comments.user.last_name }}</p></div>
            <div class="row"><label class="dateposted">Date posted:</label><p>{{ comments.date_posted }}</p></div>
            <div class="row"><label class="ratingposted">Rating:</label>{{ comments.rating }}★</div>
        </div>
        {% endfor %}
    </section>

</div>
{% endblock %}

DW-42021-prj-grp1-Luangxay/project2_products/item/templates/item/item_comment_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
    Comment Form
{% endblock title %}

{% block cssLink %}
<link type="text/css" rel="stylesheet" href="{% static 'user_management/form.css' %}">
{% endblock %}

{% block content %}
<div class="form-section">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="all-fields">
            <legend>
                Add a comment
            </legend>
            {{ form |crispy }}
        </fieldset>
        <div id="btnContainer"><button type="submit">Add Comment</button></div>
    </form>
</div>
{% endblock %}

DW-42021-prj-grp1-Luangxay/project2_products/item/templates/item/item_confirm_delete.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Confirm Delete Item
{% endblock title %}

{% block cssLink %}
<link type="text/css" rel="stylesheet" href="{% static 'user_management/form.css' %}">
{% endblock %}

{% block content %}
<div class="form-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="all-fields">
            <legend>
                Delete Item
            </legend>
            <h2>Are you sure you want to delete "{{ object.itemname }}"</h2>
        </fieldset>
        <div id="btnContainer"><button type="submit">Yes, Delete</button>
        <a href="{% url 'item-detail' object.id %}">No, Cancel</a></div>
    </form>
</div>
{% endblock %}

DW-42021-prj-grp1-Luangxay/project2_products/item/templates/item/item_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
    Item Form
{% endblock title %}

{% block cssLink %}
<link type="text/css" rel="stylesheet" href="{% static 'user_management/form.css' %}">
{% endblock %}

{% block content %}
<div class="form-section">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="all-fields">
            <legend>
                Add an item
            </legend>
            {{ form |crispy }}
        </fieldset>
        <div id="btnContainer"><button type="submit">Add</button></div>
    </form>
</div>
{% endblock %}

DW-42021-prj-grp1-Luangxay/project2_products/item/templates/item/items.html
{% extends "base.html" %}
{% load static %}

{% block title%}
    Item List
{% endblock title%}

{% block cssLink %}
<link type="text/css" rel="stylesheet" href="{% static 'item/items.css' %}">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap" rel="stylesheet">
{% endblock %}


{% block content %}
<div id="searchHeader">
    <h2>Items</h2>
    <div id="searchHeaderContent">
        <div id="formsContainer">
            <form id="searchContainer" method="GET" action="{% url 'item-search' %}">
                <input type="text" placeholder="&#x1F50E; Search here" id="searchBar" name="search">
            </form>
            <form id="filterContainer" method="GET" action="{% url 'item-filter' %}">
                <label for="filterby">Filter by: </label>
                <select name="filterby" id="filterby">
                    <option value="all">All</option>
                    <option value="likes">Likes</option>
                    <option value="food">Food</option>
                    <option value="books">Books</option>
                    <option value="clothing">Clothing</option>
                    <option value="electronics">Electronics</option>
                    <option value="instrument">Instrument</option>
                </select>
                <button>Filter</button>
            </form>
        </div>
        {% if user.is_authenticated %}
            <button id="addbutton" onclick="window.location.href='{% url 'item-create' %}'">Add Item ➕</button>
        {% endif %}
    </div>
</div>
    <div id="allitems">
    {% for item in object_list %}
        <article id="item{{ item.pk }}">
            <h2 class = "nameofitem">{{ item.itemname }}</h2>
            <p class = "genreofitem">Genre: {{ item.genre }}</p>
            <p class = "sellerofitem">Seller: {{ item.user.first_name }} </p>
            <p>Likes: {{ item.likes.count }}</p>
            {% if user.is_authenticated %}
            <button class = "detailbutton" onclick="window.location.href='/items/{{ item.id }}'">See Details 🔍</button>
            {% endif %}
        </article>
    {% endfor %}
    </div>
{% if page_obj.number > 0 %}
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}" class="pageanchor" >◀ Previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}" class="pageanchor">Next ▶</a>
            {% endif %}
        </span>
    </div>
{% endif %}
{% endblock %}