DW-42021-prj-grp1-Luangxay/project2_products/messaging/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.messaging.as_view(), name='messaging'),
    path('<str:room_name>/', views.GetRoom.as_view(), name='room'),

]

DW-42021-prj-grp1-Luangxay/project2_products/messaging/models.py
from django.db import models
from django.utils import timezone


# # Create your models here.
# Model for saved chat messages
class SavedChat(models.Model):

    savedMessages = models.CharField(max_length=1000)
    chatRoom = models.CharField(max_length=120)
    timeSent = models.DateTimeField(default=timezone.now)

    # returns the name of the chat room
    def __str__(self):
        temp = "room: " + self.chatRoom
        return temp

DW-42021-prj-grp1-Luangxay/project2_products/messaging/forms.py
from django import forms


# Form for the chat field
class MsgForm(forms.Form):
    chat_message_input = forms.CharField(max_length=1000, label='')

DW-42021-prj-grp1-Luangxay/project2_products/messaging/views.py
# messaging/views
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views.generic import ListView
from django.contrib.auth.models import User
from .models import SavedChat
from django.http import HttpResponseRedirect
from .forms import MsgForm
from administration.models import Profile


# Create your views here.
# Displays the "homepage" of messaging/ inbox
class messaging(ListView):
    template_name = "messaging/messaging_home.html"
    queryset = User.objects.all()
    context_object_name = 'users'

    # fetches all the users, and sets the user's notifications to 0
    def get(self, request):
        profileobj = Profile.objects.get(user_id=request.user.id)
        profileobj.notifications = 0
        profileobj.save()

        return render(request, self.template_name, {self.context_object_name: self.queryset, 'current': request.user})


# Displays chatroom between a specific user
class GetRoom(ListView):
    template_name = "messaging/message_page.html"
    queryset = User.objects.all()
    context_object_name = 'users'

    # fetches all the users, room name, chat room form, and user/receiver and sends it to the html
    def get(self, request, room_name):
        userobj = request.user
        receiver = self.getReceiver(room_name, userobj)
        form = MsgForm()
        savedmsg = SavedChat.objects.all().filter(chatRoom=room_name).order_by('timeSent')

        return render(request, self.template_name,
                      {'room_name': room_name, self.context_object_name: self.queryset, 'current': userobj,
                       'savedmsg': savedmsg, 'form': form, 'receiver': receiver})

    # when the user submits a message, remake the same page.
    def post(self, request, room_name):
        userobj = request.user
        receiver = self.getReceiver(room_name, userobj)
        form = MsgForm()
        savedmsg = SavedChat.objects.all().filter(chatRoom=room_name).order_by('timeSent')

        return render(request, self.template_name,
                      {'room_name': room_name, self.context_object_name: self.queryset, 'current': request.user,
                       'savedmsg': savedmsg, 'form': form, 'receiver': receiver})

    # Get the User object of the receiver base on the chat room
    # a chat room format is id1_id2, id1 being <= id2 , and one of the id corresponds to the current user id
    def getReceiver(self, room_name, userobj):

        userid = str(userobj.id)

        ids = room_name.split('_')
        id1 = ids[0]
        id2 = ids[1]

        receiverobj1 = User.objects.get(id=id1)
        receiverobj2 = User.objects.get(id=id2)

        # If the id1 is not equal to current user id
        if id1 != userid:
            return receiverobj1
        # If the id2 is not equal to the current user id
        elif id2 != userid:
            return receiverobj2
        # if both id corresponds to the userid then the user is talking in their own personal dm
        else:
            return userobj;

DW-42021-prj-grp1-Luangxay/project2_products/messaging/templates/messaging/message_page.html
{% extends "base.html" %}
{% load static %}

{% block title%}
    Message
{% endblock title%}

{% block cssLink %}
    <link type="text/css" rel="stylesheet" href="{% static 'messaging/chat.css' %}">
{% endblock %}

{% block content %}
<div id="msg_block">
    <div id="msg_friendblock">
        <h3 id="msg_dm">
            DM
        </h3>
        <ul id="msg_friendslist">

            {%  for person in users %}

                <li>
                    {% if current.id < person.id  %}
                        <a href="/messaging/{{ current.id }}_{{ person.id }}">
                            {{ person.username }}

                        </a>
                    {% endif %}
                    {% if current.id > person.id %}
                        <a href="/messaging/{{ person.id }}_{{ current.id }}">
                            {{ person.username }}

                        </a>
                    {% endif %}


                    {% if current.id == person.id %}
                        <a href="/messaging/{{ current.id }}_{{ current.id }}">
                            {{ current.username }}

                        </a>
                    {% endif %}
                </li>


            {% endfor %}
        </ul>
    </div>

    <div id="msg_chatfield">

        <h2 id="msg_title"> {{ receiver.username }} </h2>
        <textarea readonly id="chat">{% for msg in savedmsg %}{{ msg.savedMessages }}
{% endfor %}</textarea>

        <form id="chat-input" action="" method="post">
            {% csrf_token %}
            {{ form }}
<!--            <input id="id_chat_message_input" type="text">-->
            <input id="chat-message-submit" type="submit" value="Send">
        </form>

    </div>

</div>
{{ room_name|json_script:"room-name" }}
<script>

    const roomName = JSON.parse(document.getElementById('room-name').textContent);

    const chatSocket = new WebSocket(
        'ws://'
        + window.location.host
        + '/ws/messaging/'
        + roomName
        + '/'
    );

    chatSocket.onmessage = function(e) {
        const data = JSON.parse(e.data);
        document.querySelector('#chat').value += (data.message + '\n');
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#id_chat_message_input').focus();
    document.querySelector('#id_chat_message_input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick = function(e) {
        const messageInputDom = document.querySelector('#id_chat_message_input');
        const message = messageInputDom.value;
        if(message != ''){
            chatSocket.send(JSON.stringify({
                'message': "{{ current.username }}: " + message,
                'chatRoom': roomName,
                'receiver': {{ receiver.id }}
            }));
        }

        messageInputDom.value = '';
    };
</script>

{% endblock %}

DW-42021-prj-grp1-Luangxay/project2_products/messaging/templates/messaging/messaging_home.html
{% extends "base.html" %}
{% load static %}

{% block title%}
    Message Home
{% endblock title%}

{% block cssLink %}
    <link type="text/css" rel="stylesheet" href="{% static 'messaging/chat.css' %}">
{% endblock %}

{% block content %}
<div id="msg_block">
    <div id="msg_friendblock">
        <h3 id="msg_dm">
            DM
        </h3>
        <ul id="msg_friendslist">

            {%  for person in users %}

                <li>
                    {% if current.id < person.id  %}
                        <a href="/messaging/{{ current.id }}_{{ person.id }}">
                            {{ person.username }}
                        </a>
                    {% endif %}
                    {% if current.id > person.id %}
                        <a href="/messaging/{{ person.id }}_{{ current.id }}">
                            {{ person.username }}
                        </a>
                    {% endif %}

                    {% if current.id == person.id %}
                        <a href="/messaging/{{ current.id }}_{{ current.id }}">
                            {{ current.username }}
                        </a>
                    {% endif %}
                </li>

            {% endfor %}
        </ul>
    </div>

    <div id="msg_chatfield">
        <h2 id="msg_title"> Messages </h2>
    </div>

</div>

{% endblock %}